# Generated by Django 3.0.8 on 2020-07-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('picture', models.CharField(max_length=250, verbose_name='Picture')),
                ('need_to_find', models.CharField(max_length=100, verbose_name='Need to find')),
                ('found', models.CharField(max_length=100, verbose_name='Found')),
                ('time_upload', models.TimeField(auto_now_add=True, verbose_name='Upload time')),
                ('work_time', models.TimeField(auto_now_add=True, verbose_name='Work time')),
            ],
        ),
    ]
