# Generated by Django 3.0.8 on 2020-07-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='work_time',
            field=models.TimeField(verbose_name='Work time'),
        ),
    ]
